# ansible-playbook -i inventory/srv6.yml playbook/bgp.yml
---
- name: Configure BGP EVPN 
  hosts: pe
  connection: juniper.device.pyez
  gather_facts: false
  tags: juniper

  vars:
    config_dir: "{{ playbook_dir }}/tmp/bgp"
    config_filename: "{{ config_dir }}/{{ inventory_hostname }}.conf"

  tasks:
    - name: Create BGP configuration directory
      file:
          path: "{{ config_dir }}"
          state: directory
      run_once: yes

    - name: Build BGP Configuration
      template: src="bgp.j2" dest={{ config_filename }}

    - name: Apply BGP Configuration
      junos_config:
        src: "{{ config_filename }}"
      register: response
