# ansible-playbook -i inventory/srv6.yml playbook/ce_interfaces.yml
---
- name: Configure CE interfaces
  hosts: ce
  connection: juniper.device.pyez
  gather_facts: false
  tags: juniper

  vars:
    config_dir: "{{ playbook_dir }}/tmp/{{ inventory_hostname }}"
    config_filename: "{{ config_dir }}/ce_ifaces.conf"

  tasks:
    - name: Create configuration directory for CE interfaces
      file:
          path: "{{ config_dir }}"
          state: directory
      run_once: false

    - name: Build Configuration
      template: src="ce_interfaces.j2" dest={{ config_filename }}

    - name: Apply Configuration
      junos_config:
        src: "{{ config_filename }}"
      register: response
