# ansible-playbook -i inventory/srv6.yml playbook/elan.yml
---
- name: Configure EVPN ELAN Services
  hosts: pe
  connection: juniper.device.pyez
  gather_facts: false
  tags: juniper

  vars:
    config_dir: "{{ playbook_dir }}/tmp/{{ inventory_hostname }}"
    config_filename: "{{ config_dir }}/elan.conf"

  tasks:
    - name: Create ELAN service configuration directory
      file:
          path: "{{ config_dir }}"
          state: directory
      run_once: yes

    - name: Build ELAN Service Configuration
      template: src="elan.j2" dest={{ config_filename }}

    - name: Apply ELAN Service Configuration
      junos_config:
        src: "{{ config_filename }}"
      register: response
