# ansible-playbook -i inventory/srv6.yml playbook/interfaces.yml
---
- name: Assign Phys Interface to Bundle and Configure P2P IPs
  hosts: pe:p
  connection: juniper.device.pyez
  gather_facts: false
  tags: juniper

  vars:
    config_dir: "{{ playbook_dir }}/tmp/{{ inventory_hostname }}"
    config_filename_ae: "{{ config_dir }}/core_iface_ae.conf"
    config_filename_p2p: "{{ config_dir }}/core_iface_p2p.conf"

  tasks:
    - name: Create AE configuration directory
      file:
          path: "{{ config_dir }}"
          state: directory
      run_once: false

    - name: Build AE Configuration
      template: src="interfaces.j2" dest={{ config_filename_ae }}

    - name: Apply AE Configuration
      junos_config:
        src: "{{ config_filename_ae }}"
      register: response

    - name: Build P2P IP Configuration for AE
      command: "python3 {{ playbook_dir }}/library/p2p_ip.py {{ inventory_dir }}/interconnect.yml -o {{ playbook_dir }}/tmp" 
      run_once: true

    - name: Apply P2P IP Configuration for AE
      junos_config:
        src: "{{ config_filename_p2p }}"
      register: response

#    - name: Apply AE P2P Configuration
#      junos_config:
#        update: replace
#        src: "{{ config_filename_p2p }}"
#        src_format: set
#      register: response
