# ansible-playbook -i inventory/srv6.yml playbook/isis.yml
---
- name: Configure ISIS SRv6 
  hosts: pe:p
  connection: juniper.device.pyez
  gather_facts: false
  tags: juniper

  vars:
    config_dir: "{{ playbook_dir }}/tmp/{{ inventory_hostname }}"
    config_filename: "{{ config_dir }}/isis.conf"

  tasks:
    - name: Create ISIS configuration directory
      file:
          path: "{{ config_dir }}"
          state: directory
      run_once: yes

    - name: Build ISIS Configuration
      template: src="isis.j2" dest={{ config_filename }}

    - name: Apply ISIS Configuration
      junos_config:
        src: "{{ config_filename }}"
      register: response
