---
- name: "Configure Juniper Devices" 
  hosts: all:!ce
  connection: juniper.device.pyez
  gather_facts: no

  tasks:
    - name: "Base config"
      junos_config:
        lines:
          - "delete interfaces ae0"
      register: result
      diff: true
