---
- name: "Configure Juniper Devices" 
  hosts: pe
  connection: juniper.device.pyez
  gather_facts: no

  tasks:
    - name: "Base config"
      junos_config:
        lines:
          - "delete routing-instances l3vpn10"
          - "delete routing-instances l3vpn20"
      register: result
      diff: true
