# ansible-playbook -i inventory/srv6.yml playbook/services.yml
---
- name: Configure EVPN Services
  hosts: pe
  connection: juniper.device.pyez
  gather_facts: false
  tags: juniper

  vars:
    config_dir: "{{ playbook_dir }}/tmp/services"
    config_filename: "{{ config_dir }}/{{ inventory_hostname }}.conf"

  tasks:
    - name: Create service configuration directory
      file:
          path: "{{ config_dir }}"
          state: directory
      run_once: yes

    - name: Build Service Configuration
      template: src="services.j2" dest={{ config_filename }}

    - name: Apply Service Configuration
      junos_config:
        src: "{{ config_filename }}"
      register: response
