all:
  vars:
    ansible_connection: ansible.netcommon.netconf
    ansible_network_os: junipernetworks.junos.junos
    ansible_netconf_host_key_checking: false
  children:
    pe:
      hosts:
        pe1:
          ansible_host: 172.20.20.8
          bgp:
            asn: 65100
            groups:
            - name: INTERNAL
              family:
              - evpn
              - inet-vpn
              - inet6-vpn
              neighbors:
              - 2001::1:1:0:2
              - 2001::1:1:0:3
          lo0_v4: 1.1.0.1
          lo0_v6: 2001::1:1:0:1
          lo0_iso: "49.2001.0000.0101.0001.00"
          type: junos
          locators:
          - name: myloc1
            address: "1111:1111:1111::/48"
            end_sid: "1111:1111:1111::"
          - name: myloc2
            address: "2222:2222:1111::/48"
            micro_sid: true
          interfaces:
          - name: ae0
            mtu: 9192
            family:
            - iso
            members:
            - ge-0/0/0
          - name: ae1
            mtu: 9192
            family:
            - iso
            members:
            - ge-0/0/1
          srv6te:
            segment_lists:
            - name: "SL-P1->PE2->P2->PE3-loc1"
              hops:
              - name: P1
                sid: "1111:1111:4444::"
                micro_sid: false
              - name: PE2
                sid: "1111:1111:2222::"
                micro_sid: false
              - name: P2
                sid: "1111:1111:5555::"
                micro_sid: false
              - name: PE3
                sid: "1111:1111:3333::"
                micro_sid: false
            - name: "SL-P2->P1->PE3-loc1"
              hops:
              - name: P2
                sid: "1111:1111:5555::"
                micro_sid: false
              - name: P1
                sid: "1111:1111:4444::"
                micro_sid: false
              - name: PE3
                sid: "1111:1111:3333::"
                micro_sid: false
            - name: "SL-P1->PE2->P2->PE3-loc2"
              hops:
              - name: P1
                sid: "2222:2222:4444::"
                micro_sid: true
              - name: PE2
                sid: "2222:2222:2222::"
                micro_sid: true
              - name: P2
                sid: "2222:2222:5555::"
                micro_sid: true
              - name: PE3
                sid: "2222:2222:3333::"
                micro_sid: true
            - name: "SL-P2->P1->PE3-loc2"
              hops:
              - name: P2
                sid: "2222:2222:5555::"
                micro_sid: true
              - name: P1
                sid: "2222:2222:4444::"
                micro_sid: true
              - name: PE3
                sid: "2222:2222:3333::"
                micro_sid: true
            sr_paths:
            - name: "to-PE3-myloc1-color1"
              to: "1111:1111:3333::"
              primary: "SL-P1->PE2->P2->PE3-loc1"
              color: 1
            - name: "to-PE3-myloc1-color2"
              to: "1111:1111:3333::"
              primary: "SL-P2->P1->PE3-loc1"
              color: 2
            - name: "to-PE3-myloc2-color1"
              to: "2222:2222:3333::"
              primary: "SL-P1->PE2->P2->PE3-loc2"
              color: 1
            - name: "to-PE3-myloc2-color2"
              to: "2222:2222:3333::"
              primary: "SL-P2->P1->PE3-loc2"
              color: 2
          services:
            interfaces:
            - name: ae12
              mtu: 9192
              members:
              - ge-0/0/3
              esi_id: "00:01:02:00:00:00:00:00:12:00"
              system_id: "00:00:00:00:12:00"
              df_preference: 200
            - name: ge-0/0/2
              mtu: 9192
            elan:
              - name: elan200
                locator: myloc1
                micro_sid: false
                vlan_id: 200
                interfaces:
                - ae12
                - ge-0/0/2
              - name: elan201
                locator: myloc2
                micro_sid: true
                vlan_id: 201
                interfaces: 
                - ae12
                - ge-0/0/2
            vpws:
              - name: vpws100
                locator: myloc1
                end_dx2_sid: "1111:1111:1111:100::"
                local_id: 1
                remote_id: 2
                vlan_id: 100
                interface: ae12
              - name: vpws101
                locator: myloc1
                local_id: 1
                remote_id: 2
                vlan_id: 101
                interface: ae12
            l3vpn:
              - name: l3vpn10
                locator: myloc1
                end_dt46_sid: "1111:1111:1111:10::"
                interface: ge-0/0/2
                vlan_id: 10
                ipv4: "192.168.11.1/24"
                ipv6: "::192:168:11:1/112"
                colors:
                - id: 1
                  prefixes:
                  - "192.168.11.0/24"
                - id: 2
                  prefixes:
                  - "::192:168:11:0/112"
              - name: l3vpn20
                locator: myloc2
                micro_dt46_sid: true
                interface: ge-0/0/2
                vlan_id: 20
                ipv4: "192.168.21.1/24"
                ipv6: "::192:168:21:1/112"
                colors:
                - id: 1
                  prefixes:
                  - "192.168.21.0/24"
                - id: 2
                  prefixes:
                  - "::192:168:21:0/112"
        pe2:
          ansible_host: 172.20.20.6
          bgp:
            asn: 65100
            groups:
            - name: INTERNAL
              family:
              - evpn
              - inet-vpn
              - inet6-vpn
              neighbors:
              - 2001::1:1:0:1
              - 2001::1:1:0:3
          lo0_v4: 1.1.0.2
          lo0_v6: 2001::1:1:0:2
          lo0_iso: "49.2001.0000.0101.0002.00"
          type: junos
          locators:
          - name: myloc1
            address: "1111:1111:2222::/48"
            end_sid: "1111:1111:2222::"
          - name: myloc2
            address: "2222:2222:2222::/48"
            micro_sid: true
          interfaces:
          - name: ae2
            mtu: 9192
            family:
            - iso
            members:
            - ge-0/0/1
          - name: ae3
            mtu: 9192
            family:
            - iso
            members:
            - ge-0/0/0
          srv6te:
            segment_lists:
            - name: "SL-to-PE3"
              hops:
              - name: P2
                sid: "2222:2222:5555::"
                micro_sid: true
              - name: PE1
                sid: "2222:2222:1111::"
                micro_sid: true
              - name: P1
                sid: "2222:2222:4444::"
                micro_sid: true
              - name: PE3
                sid: "2222:2222:3333::"
                micro_sid: true
            sr_paths:
            - name: "to-PE3-myloc2"
              to: "2222:2222:3333::"
              primary: "SL-to-PE3"
          services:
            interfaces:
            - name: ae12
              mtu: 9192
              members:
              - ge-0/0/3
              esi_id: "00:01:02:00:00:00:00:00:12:00"
              system_id: "00:00:00:00:12:00"
              df_preference: 100
            - name: ge-0/0/2
              mtu: 9192
            elan:
              - name: elan200
                locator: myloc1
                micro_sid: false
                vlan_id: 200
                interfaces: 
                - ae12
                - ge-0/0/2
              - name: elan201
                locator: myloc2
                micro_sid: true
                vlan_id: 201
                interfaces: 
                - ae12
                - ge-0/0/2
            vpws:
              - name: vpws100
                locator: myloc1
                end_dx2_sid: "1111:1111:2222:100::"
                local_id: 1
                remote_id: 2
                vlan_id: 100
                interface: ae12
              - name: vpws101
                locator: myloc1
                local_id: 1
                remote_id: 2
                vlan_id: 101
                interface: ae12
            l3vpn:
              - name: l3vpn10
                locator: myloc1
                end_dt46_sid: "1111:1111:2222:10::"
                interface: ge-0/0/2
                vlan_id: 10
                ipv4: "192.168.12.1/24"
                ipv6: "::192:168:12:1/112"
                colors:
                - id: 1
                  prefixes:
                  - "192.168.12.0/24"
                - id: 2
                  prefixes:
                  - "::192:168:12:0/112"
              - name: l3vpn20
                locator: myloc2
                micro_dt46_sid: true
                interface: ge-0/0/2
                vlan_id: 20
                ipv4: "192.168.22.1/24"
                ipv6: "::192:168:22:1/112"
                colors:
                - id: 1
                  prefixes:
                  - "192.168.22.0/24"
                - id: 2
                  prefixes:
                  - "::192:168:22:0/112"
        pe3:
          ansible_host: 172.20.20.3
          bgp:
            asn: 65100
            groups:
            - name: INTERNAL
              family:
              - evpn
              - inet-vpn
              - inet6-vpn
              neighbors:
              - 2001::1:1:0:1
              - 2001::1:1:0:2
          lo0_v4: 1.1.0.3
          lo0_v6: 2001::1:1:0:3
          lo0_iso: "49.2001.0000.0101.0003.00"
          type: junos
          locators:
          - name: myloc1
            address: "1111:1111:3333::/48"
            end_sid: "1111:1111:3333::"
          - name: myloc2
            address: "2222:2222:3333::/48"
            micro_sid: true
          interfaces:
          - name: ae5
            mtu: 9192
            family:
            - iso
            members:
            - ge-0/0/0
          - name: ae6
            mtu: 9192
            family:
            - iso
            members:
            - ge-0/0/1
          services:
            interfaces:
            - name: ge-0/0/2
              mtu: 9192
            elan:
              - name: elan200
                locator: myloc1
                micro_sid: false
                vlan_id: 200
                interfaces: 
                - ge-0/0/2
              - name: elan201
                locator: myloc2
                micro_sid: true
                vlan_id: 201
                interfaces:
                - ge-0/0/2
            vpws:
              - name: vpws100
                locator: myloc1
                end_dx2_sid: "1111:1111:3333:100::"
                local_id: 2
                remote_id: 1
                vlan_id: 100
                interface: ge-0/0/2
              - name: vpws101
                locator: myloc1
                local_id: 2
                remote_id: 1
                vlan_id: 101
                interface: ge-0/0/2
            l3vpn:
              - name: l3vpn10
                locator: myloc1
                end_dt46_sid: "1111:1111:3333:10::"
                interface: ge-0/0/2
                vlan_id: 10
                ipv4: "192.168.13.1/24"
                ipv6: "::192:168:13:1/112"
                colors:
                - id: 1
                  prefixes:
                  - "192.168.13.0/24"
                - id: 2
                  prefixes:
                  - "::192:168:13:0/112"
              - name: l3vpn20
                locator: myloc2
                micro_dt46_sid: true
                interface: ge-0/0/2
                vlan_id: 20
                ipv4: "192.168.23.1/24"
                ipv6: "::192:168:23:1/112"
                colors:
                - id: 1
                  prefixes:
                  - "192.168.23.0/24"
                - id: 2
                  prefixes:
                  - "::192:168:23:0/112"
    p:
      hosts:
        p1:
          ansible_host: 172.20.20.9
          lo0_v4: 1.1.0.4
          lo0_v6: 2001::1:1:0:4
          lo0_iso: "49.2001.0000.0101.0004.00"
          type: junos
          locators:
          - name: myloc1
            address: "1111:1111:4444::/48"
            end_sid: "1111:1111:4444::"
          - name: myloc2
            address: "2222:2222:4444::/48"
            micro_sid: true
          interfaces:
          - name: ae0
            mtu: 9192
            family:
            - iso
            members:
            - ge-0/0/0
          - name: ae2
            mtu: 9192
            family:
            - iso
            members:
            - ge-0/0/1
          - name: ae4
            mtu: 9192
            family:
            - iso
            members:
            - ge-0/0/2
          - name: ae5
            mtu: 9192
            family:
            - iso
            members:
            - ge-0/0/3
        p2:
          ansible_host: 172.20.20.10
          lo0_v4: 1.1.0.5
          lo0_v6: 2001::1:1:0:5
          lo0_iso: "49.2001.0000.0101.0005.00"
          type: junos
          locators:
          - name: myloc1
            address: "1111:1111:5555::/48"
            end_sid: "1111:1111:5555::"
          - name: myloc2
            address: "2222:2222:5555::/48"
            micro_sid: true
          interfaces:
          - name: ae3
            mtu: 9192
            family:
            - iso
            members:
            - ge-0/0/0
          - name: ae1
            mtu: 9192
            family:
            - iso
            members:
            - ge-0/0/1
          - name: ae4
            mtu: 9192
            family:
            - iso
            members:
            - ge-0/0/2
          - name: ae6
            mtu: 9192
            family:
            - iso
            members:
            - ge-0/0/3
    ce:
      hosts:
        ce1:
          ansible_host: 172.20.20.7
          lo0_v4: 1.1.0.101
          lo0_v6: 2001::1:1:0:101
          lo0_iso: "49.2001.0000.0101.0101.00"
          type: junos
          interfaces:
          - name: ge-0/0/0
            mtu: 9192
            vlans:
            - 10
            - 20
            - 200
            - 201
          vlans:
          - name: vlan10
            id: 10
            ip_v4: "192.168.11.2/24"
            ip_v6: "::192:168:11:2/112"
          - name: vlan20
            id: 20
            ip_v4: "192.168.21.2/24"
            ip_v6: "::192:168:21:2/112"
          - name: vlan200
            id: 200
            ip_v4: "192.168.200.1/24"
            ip_v6: "::192:168:200:1/112"
          - name: vlan201
            id: 201
            ip_v4: "192.168.201.1/24"
            ip_v6: "::192:168:201:1/112"
          virtual_routers:
          - name: VR10
            v4_gw: "192.168.11.1"
            v6_gw: "::192:168:11:1"
            interfaces:
            - irb.10
          - name: VR20
            v4_gw: "192.168.21.1"
            v6_gw: "::192:168:21:1"
            interfaces:
            - irb.20
        ce12:
          ansible_host: 172.20.20.4
          lo0_v4: 1.1.0.112
          lo0_v6: 2001::1:1:0:112
          lo0_iso: "49.2001.0000.0101.0112.00"
          type: junos
          interfaces:
          - name: ae12
            mtu: 9192
            members:
            - ge-0/0/0
            - ge-0/0/1
            vlans:
            - 100
            - 101
            - 200
            - 201
          vlans:
          - name: vlan100
            id: 100
            ip_v4: "192.168.100.12/24"
            ip_v6: "::192:168:100:12/112"
          - name: vlan101
            id: 101
            ip_v4: "192.168.101.12/24"
            ip_v6: "::192:168:101:12/112"
          - name: vlan200
            id: 200
            ip_v4: "192.168.200.12/24"
            ip_v6: "::192:168:200:12/112"
          - name: vlan201
            id: 201
            ip_v4: "192.168.201.12/24"
            ip_v6: "::192:168:201:12/112"
        ce2:
          ansible_host: 172.20.20.2
          lo0_v4: 1.1.0.102
          lo0_v6: 2001::1:1:0:102
          lo0_iso: "49.2001.0000.0101.0102.00"
          type: junos
          interfaces:
          - name: ge-0/0/0
            mtu: 9192
            vlans:
            - 10
            - 20
            - 200
            - 201
          vlans:
          - name: vlan10
            id: 10
            ip_v4: "192.168.12.2/24"
            ip_v6: "::192:168:12:2/112"
          - name: vlan20
            id: 20
            ip_v4: "192.168.22.2/24"
            ip_v6: "::192:168:22:2/112"
          - name: vlan200
            id: 200
            ip_v4: "192.168.200.2/24"
            ip_v6: "::192:168:200:2/112"
          - name: vlan201
            id: 201
            ip_v4: "192.168.201.2/24"
            ip_v6: "::192:168:201:2/112"
          virtual_routers:
          - name: VR10
            v4_gw: "192.168.12.1"
            v6_gw: "::192:168:12:1"
            interfaces:
            - irb.10
          - name: VR20
            v4_gw: "192.168.22.1"
            v6_gw: "::192:168:22:1"
            interfaces:
            - irb.20
        ce3:
          ansible_host: 172.20.20.5
          lo0_v4: 1.1.0.103
          lo0_v6: 2001::1:1:0:103
          lo0_iso: "49.2001.0000.0101.0103.00"
          type: junos
          interfaces:
          - name: ge-0/0/0
            mtu: 9192
            vlans:
            - 10
            - 20
            - 100
            - 101
            - 200
            - 201
          vlans:
          - name: vlan10
            id: 10
            ip_v4: "192.168.13.2/24"
            ip_v6: "::192:168:13:2/112"
          - name: vlan20
            id: 20
            ip_v4: "192.168.23.2/24"
            ip_v6: "::192:168:23:2/112"
          - name: vlan100
            id: 100
            ip_v4: "192.168.100.3/24"
            ip_v6: "::192:168:100:3/112"
          - name: vlan101
            id: 101
            ip_v4: "192.168.101.3/24"
            ip_v6: "::192:168:101:3/112"
          - name: vlan200
            id: 200
            ip_v4: "192.168.200.3/24"
            ip_v6: "::192:168:200:3/112"
          - name: vlan201
            id: 201
            ip_v4: "192.168.201.3/24"
            ip_v6: "::192:168:201:3/112"
          virtual_routers:
          - name: VR10
            v4_gw: "192.168.13.1"
            v6_gw: "::192:168:13:1"
            interfaces:
            - irb.10
          - name: VR20
            v4_gw: "192.168.23.1"
            v6_gw: "::192:168:23:1"
            interfaces:
            - irb.20
