all:
  vars:
    ansible_connection: ansible.netcommon.netconf
    ansible_network_os: junipernetworks.junos.junos
    ansible_netconf_host_key_checking: false
  children:
    pe:
      hosts:
        pe1:
          ansible_host: 172.20.20.8
          bgp:
            asn: 65100
            groups:
            - name: INTERNAL
              family:
              - evpn
              - inet-vpn
              - inet6-vpn
              neighbors:
              - 2001::1:1:0:2
              - 2001::1:1:0:3
          lo0_v4: 1.1.0.1
          lo0_v6: 2001::1:1:0:1
          lo0_iso: "49.2001.0000.0101.0001.00"
          type: junos
          locators:
          - name: myloc1
            address: "1111:1111:1111::/48"
            end_sid: "1111:1111:1111::"
          - name: myloc2
            address: "2222:2222:1111::/48"
            micro_sid: true
          interfaces:
          - name: ae0
            mtu: 9192
            family:
            - iso
            members:
            - ge-0/0/0
          - name: ae1
            mtu: 9192
            family:
            - iso
            members:
            - ge-0/0/1
          services:
            interfaces:
            - name: ae10
              mtu: 9192
              members:
              - ge-0/0/2
              esi_id: "00:01:02:00:00:00:00:00:10:00"
              system_id: "00:00:00:00:10:00"
              df_preference: 200
            - name: ge-0/0/3
              mtu: 9192
            elan:
              - name: elan200
                locator: myloc2
                micro_sid: true
                vlan_id: 200
                interface: ae10
              - name: elan201
                locator: myloc2
                micro_sid: true
                vlan_id: 201
                interface: ae10
            vpws:
              - name: vpws100
                locator: myloc1
                end_dx2_sid: "1111:1111:1111:100::"
                local_id: 1
                remote_id: 2
                vlan_id: 100
                interface: ae10
              - name: vpws101
                locator: myloc1
                local_id: 1
                remote_id: 2
                vlan_id: 101
                interface: ae10
            l3vpn:
              - name: l3vpn10
                locator: myloc1
                end_dt46_sid: "1111:1111:1111:10::"
                interface: ge-0/0/3
                vlan_id: 10
                ipv4: "192.168.11.1/24"
                ipv6: "::192:168:11:1/112"
              - name: l3vpn20
                locator: myloc2
                micro_dt46_sid: true
                interface: ge-0/0/3
                vlan_id: 20
                ipv4: "192.168.21.1/24"
                ipv6: "::192:168:21:1/112"
        pe2:
          ansible_host: 172.20.20.6
          bgp:
            asn: 65100
            groups:
            - name: INTERNAL
              family:
              - evpn
              - inet-vpn
              - inet6-vpn
              neighbors:
              - 2001::1:1:0:1
              - 2001::1:1:0:3
          lo0_v4: 1.1.0.2
          lo0_v6: 2001::1:1:0:2
          lo0_iso: "49.2001.0000.0101.0002.00"
          type: junos
          locators:
          - name: myloc1
            address: "1111:1111:2222::/48"
            end_sid: "1111:1111:2222::"
          - name: myloc2
            address: "2222:2222:2222::/48"
            micro_sid: true
          interfaces:
          - name: ae2
            mtu: 9192
            family:
            - iso
            members:
            - ge-0/0/1
          - name: ae3
            mtu: 9192
            family:
            - iso
            members:
            - ge-0/0/0
          services:
            interfaces:
            - name: ae10
              mtu: 9192
              members:
              - ge-0/0/2
              esi_id: "00:01:02:00:00:00:00:00:10:00"
              system_id: "00:00:00:00:10:00"
              df_preference: 100
            - name: ge-0/0/3
              mtu: 9192
            elan:
              - name: elan200
                locator: myloc2
                micro_sid: true
                vlan_id: 200
                interface: ae10
              - name: elan201
                locator: myloc2
                micro_sid: true
                vlan_id: 201
                interface: ae10
            vpws:
              - name: vpws100
                locator: myloc1
                end_dx2_sid: "1111:1111:2222:100::"
                local_id: 1
                remote_id: 2
                vlan_id: 100
                interface: ae10
              - name: vpws101
                locator: myloc1
                local_id: 1
                remote_id: 2
                vlan_id: 101
                interface: ae10
            l3vpn:
              - name: l3vpn10
                locator: myloc1
                end_dt46_sid: "1111:1111:2222:10::"
                interface: ge-0/0/3
                vlan_id: 10
                ipv4: "192.168.12.1/24"
                ipv6: "::192:168:12:1/112"
              - name: l3vpn20
                locator: myloc2
                micro_dt46_sid: true
                interface: ge-0/0/3
                vlan_id: 20
                ipv4: "192.168.22.1/24"
                ipv6: "::192:168:22:1/112"
        pe3:
          ansible_host: 172.20.20.5
          bgp:
            asn: 65100
            groups:
            - name: INTERNAL
              family:
              - evpn
              - inet-vpn
              - inet6-vpn
              neighbors:
              - 2001::1:1:0:1
              - 2001::1:1:0:2
          lo0_v4: 1.1.0.3
          lo0_v6: 2001::1:1:0:3
          lo0_iso: "49.2001.0000.0101.0003.00"
          type: junos
          locators:
          - name: myloc1
            address: "1111:1111:3333::/48"
            end_sid: "1111:1111:3333::"
          - name: myloc2
            address: "2222:2222:3333::/48"
            micro_sid: true
          interfaces:
          - name: ae5
            mtu: 9192
            family:
            - iso
            members:
            - ge-0/0/0
          - name: ae6
            mtu: 9192
            family:
            - iso
            members:
            - ge-0/0/1
          services:
            interfaces:
            - name: ae20
              mtu: 9192
              members:
              - ge-0/0/2
            elan:
              - name: elan200
                locator: myloc2
                micro_sid: true
                vlan_id: 200
                interface: ae20
              - name: elan201
                locator: myloc2
                micro_sid: true
                vlan_id: 201
                interface: ae20
            vpws:
              - name: vpws100
                locator: myloc1
                end_dx2_sid: "1111:1111:3333:100::"
                local_id: 2
                remote_id: 1
                vlan_id: 100
                interface: ae20
              - name: vpws101
                locator: myloc1
                local_id: 2
                remote_id: 1
                vlan_id: 101
                interface: ae20
            l3vpn:
              - name: l3vpn10
                locator: myloc1
                end_dt46_sid: "1111:1111:3333:10::"
                interface: ae20
                vlan_id: 10
                ipv4: "192.168.13.1/24"
                ipv6: "::192:168:13:1/112"
              - name: l3vpn20
                locator: myloc2
                micro_dt46_sid: true
                interface: ae20
                vlan_id: 20
                ipv4: "192.168.23.1/24"
                ipv6: "::192:168:23:1/112"
    p:
      hosts:
        p1:
          ansible_host: 172.20.20.4
          lo0_v4: 1.1.0.4
          lo0_v6: 2001::1:1:0:4
          lo0_iso: "49.2001.0000.0101.0004.00"
          type: junos
          locators:
          - name: myloc1
            address: "1111:1111:4444::/48"
            end_sid: "1111:1111:4444::"
          interfaces:
          - name: ae0
            mtu: 9192
            family:
            - iso
            members:
            - ge-0/0/0
          - name: ae2
            mtu: 9192
            family:
            - iso
            members:
            - ge-0/0/1
          - name: ae4
            mtu: 9192
            family:
            - iso
            members:
            - ge-0/0/2
          - name: ae5
            mtu: 9192
            family:
            - iso
            members:
            - ge-0/0/3
        p2:
          ansible_host: 172.20.20.7
          lo0_v4: 1.1.0.5
          lo0_v6: 2001::1:1:0:5
          lo0_iso: "49.2001.0000.0101.0005.00"
          type: junos
          locators:
          - name: myloc1
            address: "1111:1111:5555::/48"
            end_sid: "1111:1111:5555::"
          interfaces:
          - name: ae3
            mtu: 9192
            family:
            - iso
            members:
            - ge-0/0/0
          - name: ae1
            mtu: 9192
            family:
            - iso
            members:
            - ge-0/0/1
          - name: ae4
            mtu: 9192
            family:
            - iso
            members:
            - ge-0/0/2
          - name: ae6
            mtu: 9192
            family:
            - iso
            members:
            - ge-0/0/3
    ce:
      hosts:
        ce1:
          ansible_host: 172.20.20.2
          lo0_v4: 1.1.0.101
          lo0_v6: 2001::1:1:0:101
          lo0_iso: "49.2001.0000.0101.0101.00"
          type: junos
          interfaces:
          - name: ae10
            mtu: 9192
            members:
            - ge-0/0/0
            - ge-0/0/1
            vlans:
            - 100
            - 101
            - 200
            - 201
          vlans:
          - name: vlan100
            id: 100
            ip_v4: "192.168.100.1/24"
            ip_v6: "2001::192:168:100:1/112"
          - name: vlan101
            id: 101
            ip_v4: "192.168.101.1/24"
            ip_v6: "2001::192:168:101:1/112"
          - name: vlan200
            id: 200
            ip_v4: "192.168.200.1/24"
            ip_v6: "2001::192:168:200:1/112"
          - name: vlan201
            id: 201
            ip_v4: "192.168.201.1/24"
            ip_v6: "2001::192:168:201:1/112" 
        ce2:
          ansible_host: 172.20.20.3
          lo0_v4: 1.1.0.102
          lo0_v6: 2001::1:1:0:102
          lo0_iso: "49.2001.0000.0101.0102.00"
          type: junos
          interfaces:
          - name: ae20
            mtu: 9192
            members:
            - ge-0/0/0
            vlans:
            - 10
            - 20
            - 100
            - 101
            - 200
            - 201
          vlans:
          - name: vlan10
            id: 10
            ip_v4: "192.168.13.2/24"
            ip_v6: "2001::192:168:13:2/112"
          - name: vlan20
            id: 20
            ip_v4: "192.168.23.2/24"
            ip_v6: "2001::192:168:23:2/112"
          - name: vlan100
            id: 100
            ip_v4: "192.168.100.2/24"
            ip_v6: "2001::192:168:100:2/112"
          - name: vlan101
            id: 101
            ip_v4: "192.168.101.2/24"
            ip_v6: "2001::192:168:101:2/112"
          - name: vlan200
            id: 200
            ip_v4: "192.168.200.2/24"
            ip_v6: "2001::192:168:200:2/112"
          - name: vlan201
            id: 201
            ip_v4: "192.168.201.2/24"
            ip_v6: "2001::192:168:201:2/112"
          virtual_routers:
          - name: VR10
            v4_gw: "192.168.13.1"
            v6_gw: "2001::192:168:13:1"
            interfaces:
            - irb.10
          - name: VR20
            v4_gw: "192.168.23.1"
            v6_gw: "2001::192:168:23:1"
            interfaces:
            - irb.20
